services:
  mysql:
    image: mysql:8.0
    container_name: shopwave-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopwavefusion
    ports:
      - "3307:3306"
    volumes:
      - shopwave_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shopwave-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  shopwave_mysql_data: